### ISSUE TITLE
Broken with gedit >= 3.12

### ISSUE THREAD

**Issue by mcepl** [guillaumechereau/gedit-reflow-plugin#10]
```
matej@mitmanek: gedit-reflow-plugin (python2 *)$ gedit reflow.py
Traceback (most recent call last):
  File "/home/matej/.local/share/gedit/plugins/reflow.py", line 48, in do_activate
    manager = self.window.get_ui_manager()
AttributeError: 'Window' object has no attribute 'get_ui_manager'
object of type `GtkSourceStyle' does not have property `weight-set'
Traceback (most recent call last):
  File "/home/matej/.local/share/gedit/plugins/reflow.py", line 66, in do_deactivate
    manager = self.window.get_ui_manager()
AttributeError: 'Window' object has no attribute 'get_ui_manager'
```
Whole [discussion on new API](https://wiki.gnome.org/Apps/Gedit/PythonPluginHowTo) is relevant, I guess.

**Comment by guillaumechereau** [comment]
I have the same bug on my machine (debian testing) with gedit 3.14.  It seems that the plugins API has changed, but I cannot find any documentation about it.

**Comment by mcepl** [comment]
> but I cannot find any documentation about it.

The URL I have linked to?
